Add GRS
Groestlcoin/btcrecover pull request #1
Opened 2020-07-01 05:36 UTC by HashEngineering

2020-07-01 11:46 UTC, gruve-p commented
Services for groestlsight (you can copy from insightdash.py) and groestlcoinesplora (copy from blockstream.py) should be added in https://github.com/Groestlcoin/btcrecover/tree/master/bitcoinlib/services. Maybe also add blockchair into https://github.com/Groestlcoin/btcrecover/blob/master/bitcoinlib/data/providers.examples.json and https://github.com/Groestlcoin/btcrecover/blob/master/bitcoinlib/data/providers.json for now

2020-07-01 11:49 UTC, gruve-p requested changes
Services for groestlsight (you can copy from bitcoinlib/services/insightdash.py) and groestlcoinesplora (copy from bitcoinlib/services/blockstream.py) should be added in bitcoinlib/services/. Maybe also add blockchair into bitcoinlib/data/providers.examples.json and bitcoinlib/data/providers.json for now. Is this implementation tested? Is importing groestlcoin_hash not needed for base58 checksum? Also we need to add unit tests for GRS on bitcoinlib/tests

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/networks.json
> +    "currency_name_plural": "Groestlcoins",
"currency_name_plural": "groestlcoins",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +    "network": "bitcoin",
"network": "groestlcoin",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +    "network": "testnet",
"network": "groestlcoin_testnet",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +  "groesltcoinesplora": {
"groestlcoinesplora": {

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +    "provider": "groesltcoinesplora",
"provider": "groestlcoinesplora",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +  "groesltcoinesplora.testnet": {
"groestlcoinesplora.testnet": {

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +    "network": "groestlcoin.testnet",
"network": "groestlcoin_testnet",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +    "provider": "groesltcoinesplora",
"provider": "groestlcoinesplora",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +    "network": "groestlcoin.testnet",
"network": "groestlcoin_testnet",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.examples.json
> +    "network": "groestlcoin.testnet",
"network": "groestlcoin_testnet",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "network_overrides": null
Not sure if these should be included in the providers.json

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +  "groesltcoinesplora": {
"groestlcoinesplora": {

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "provider": "groesltcoinesplora",
"provider": "groestlcoinesplora",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +  "groesltcoinesplora.testnet": {
"groestlcoinesplora.testnet": {

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "provider": "groesltcoinesplora",
"provider": "groestlcoinesplora",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "network": "groestlcoin.testnet",
"network": "groestlcoin_testnet",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "network": "groestlcoin.testnet",
"network": "groestlcoin_testnet",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "network": "groestlcoin.testnet",
"network": "groestlcoin_testnet",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "client_class": "InsightDashClient",
"client_class": "GroestlsightClient",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "client_class": "InsightDashClient",
"client_class": "GroestlsightClient",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "client_class": "BlockstreamClient",
"client_class": "GroestlcoinEsploraClient",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/data/providers.json
> +    "client_class": "BlockstreamClient",
"client_class": "GroestlcoinEsploraClient",

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +    Class to interact with groestlcoind, the Bitcoin deamon
Class to interact with groestlcoind, the Groestlcoin deamon

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +    def from_config(configfile=None, network='bitcoin'):
def from_config(configfile=None, network='groestlcoin'):

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +        :param network: Bitcoin mainnet or testnet. Default is bitcoin mainnet
:param network: Groestlcoin mainnet or testnet. Default is groestlcoin mainnet

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +                                '~/Library/Application Support/Bitcoin']
config_locations = ['~/.bitcoinlib', '~/.groestlcoin', '~/Application Data/Groestlcoin',
                                '~/Library/Application Support/Groestlcoin']

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +                              "reference to an external server." % cfn)
raise ConfigError("Config file %s not found. Please install groestlcoin client and specify a path to config "
                              "file if path is not default. Or place a config file in .bitcoinlib/groestlcoin.conf to "
                              "reference to an external server." % cfn)

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +            port = 8332
port = 1441

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +            port = 18332
port = 17766

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +    def __init__(self, network='bitcoin', base_url='', denominator=100000000, *args):
`def __init__(self, network='groestlcoin', base_url='', denominator=100000000, *args):`

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +            config_fn = 'bitcoin-testnet.conf'
config_fn = 'groestlcoin-testnet.conf'

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +        config_fn = 'bitcoin.conf'
config_fn = 'groestlcoin.conf'

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +        Open connection to bitcoin node
Open connection to groestlcoin node

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +        :param network: Bitcoin mainnet or testnet. Default is bitcoin mainnet
:param network: Groestlcoin mainnet or testnet. Default is groestlcoin mainnet

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +        :param denominator: Denominator for this currency. Should be always 100000000 (satoshis) for bitcoin
:param denominator: Denominator for this currency. Should be always 100000000 (gros) for groestlcoin

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +                              "current format is %s. Please set url in providers.json file or check bitcoin config "
"current format is %s. Please set url in providers.json file or check groestlcoin config "

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +                              "Please replace default password and set url in providers.json or bitcoin.conf file")
"Please replace default password and set url in providers.json or groestlcoin.conf file")

2020-07-01 11:49 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +    # base_url = 'http://bitcoinrpc:passwd@host:8332'
`# base_url = 'http://RpcUsername:RpcPass@host:1441`

2020-07-01 23:26 UTC, Stouse49 commented
> Services for groestlsight (you can copy from bitcoinlib/services/insightdash.py) and groestlcoinesplora (copy from bitcoinlib/services/blockstream.py) should be added in bitcoinlib/services/. Maybe also add blockchair into bitcoinlib/data/providers.examples.json and bitcoinlib/data/providers.json for now. Is this implementation tested? Is importing groestlcoin_hash not needed for base58 checksum? Also we need to add unit tests for GRS on bitcoinlib/tests

We may not need to copy those files to use those services.  If the implementation is the same, then its probably better not to, but we shall see.

2020-07-02 06:43 UTC, gruve-p requested changes
Please rename bitcoinlib/services/groesltcoinesplora.py to bitcoinlib/services/groestlcoinesplora.py

2020-07-02 06:43 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +                              "file if path is not default. Or place a config file in .groestlcoinlib/groestlcoin.conf to "
.groestlcoinlib > .bitcoinlib

2020-07-02 06:43 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +            config_locations = ['~/.groestlcoinlib', '~/.groestlcoin', '~/Application Data/Groestlcoin',
.groestlcoinlib > .bitcoinlib

2020-07-02 06:43 UTC, gruve-p commented on bitcoinlib/services/groesltcoinesplora.py
> +class GroesltcoinEsploraClient(BaseClient):
class GroestlcoinEsploraClient(BaseClient):

2020-07-03 06:51 UTC, gruve-p commented on bitcoinlib/data/providers.json
>  }
},
  "blockchair.groestlcoin": {
    "provider": "blockchair",
    "network": "groestlcoin",
    "client_class": "BlockChairClient",
    "provider_coin_id": "",
    "url": "https://api.blockchair.com/groestlcoin/",
    "api_key": "",
    "priority": 10,
    "denominator": 100000000,
    "network_overrides": null

2020-07-03 06:51 UTC, gruve-p commented on bitcoinlib/data/providers.json
>  }
please add blockchair for grs also in providers.json

2020-07-03 06:51 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +                              "file if path is not default. Or place a config file in .groestlcoinlib/groestlcoin.conf to "
this is not resolved yet

2020-07-03 06:51 UTC, gruve-p commented on bitcoinlib/services/groestlcoind.py
> +            config_locations = ['~/.groestlcoinlib', '~/.groestlcoin', '~/Application Data/Groestlcoin',
this is not resolved yet

2020-07-22 09:49 UTC, closed without merging